services:
  - type: web
    name: zudoku-backend
    env: node
    buildCommand: "npm ci && npx tsx scripts/manage-openapi.ts"
    startCommand: "npx tsx server.ts"
    envVars:
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_JWKS_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ZUDOKU_PUBLIC_BACKEND_URL
        sync: false
      - key: NODE_ENV
        sync: false
      - key: PORT
        sync: false
      - key: gmail_UNSPLASH_KEY
        sync: false
    # Add your API keys as secrets in Render dashboard
    secrets:
